export const ALL_PRODUCTS_REQUEST = "ALL_PRODUCTS_REQUEST";
export const ALL_PRODUCTS_SUCCESS = "ALL_PRODUCTS_SUCCESS"
export const ALL_PRODUCTS_FAIL = "ALL_PRODUCTS_FAIL";

export const ALL_TICKETS_REQUEST = "ALL_TICKETS_REQUEST";
export const ALL_TICKETS_SUCCESS = "ALL_TICKETS_SUCCESS"
export const ALL_TICKETS_FAIL = "ALL_TICKETS_FAIL";

export const ALL_NEWS_REQUEST = "ALL_TICKETS_REQUEST";
export const ALL_NEWS_SUCCESS = "ALL_TICKETS_SUCCESS"
export const ALL_NEWS_FAIL = "ALL_TICKETS_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"


export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"


export const ADD_BASKET = "ADD_BASKET"
export const REMOVE_BASKET = "REMOVE_BASKET"

export const ADD_TICKET = "ADD_TICKET"
export const REMOVE_TICKET = "REMOVE_TICKET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"